name: Header
label: Header
labelField: title
fields:
  - type: string
    name: title
    label: Title
    default: Your Brand
  - type: image
    name: logo
    label: Logo
  - type: list
    items:
      type: string
    name: primaryLinks
    label: Primary links
  - type: list
    name: secondaryLinks
    label: Secondary links
    items:
      type: string
